### ISSUE TITLE
`@weave.type()` does not work with pydantic `BaseModel`

### ISSUE THREAD

**Issue by willbakst** [wandb/weave#1380] opened 2024-03-27 19:12 UTC
Example buggy code below outputs `AttributeError: 'Book' object has no attribute '__pydantic_fields_set__'`

```python
import weave
from pydantic import BaseModel


@weave.type()
class Book(BaseModel):
    title: str
    author: str


book = Book(title="title", author="author")
```

**Comment by scottire** [comment] 2024-04-11 12:12
This should be fixed if you inherit instead from `weave.Object` rather than using `weave.type()`

```python
import weave
from pydantic import BaseModel


class Book(weave.Object, BaseModel):
    title: str
    author: str

@weave.op()
def use_book(book: Book):
    print(f"Title: {book.title}, Author: {book.author}")
    return book.title

weave.init('william')
book = Book(title="title", author="author")
print(book.__pydantic_fields_set__)
use_book(book)
print(book.__pydantic_fields_set__)
```

**Closed by scottire** 2024-04-11 12:12 UTC

**Comment by mikeedjones** [comment] 2024-08-15 14:19
I'm not sure that this pretty drastic change to the codebase should be necessary to enable tracing of functions which use pydantic? Is there an issue to address this and improve developer experience? Can the args be recast inside weave.op instead?

**Comment by patricknnamdi** [comment] 2024-08-15 14:28
For pre-existing codebases having to adapt every model to include weave.Object is quite inconvenient. Additionally, it would be immensely helpful if this was in the docs somewhere. Unfortunately, getting weave to work with my application wasn't as simple as adding decorators everywhere due to this issue.

**Comment by andrewtruong** [comment] 2024-08-15 15:11
Hey @mikeedjones , @patricknnamdi 

You're right -- inheriting from `weave.Object` should not be necessary to enable function tracing, and fortunately it's not!

Hopefully the minimal example below is more clear at highlighting:
1. You don't need to change your objects to inherit from `weave.Object`;
2. You just need to apply the `@weave.op` decorator on top of the function you want to trace
3. We don't muck with your existing objects, but they are still tracked and available to view in the UI

```py
import weave
from pydantic import BaseModel


class Book(BaseModel):
    title: str
    author: str


@weave.op
def use_book(book: Book) -> str:
    return f"Hello, we are using {book.title} by {book.author}"


weave.init("testing78")

book = Book(title="Much Ado About Nothing", author="William Shakespeare")
use_book(book)
```
![image](https://github.com/user-attachments/assets/721f03d6-3391-4be1-a091-75d3d6e6e98c)
![image](https://github.com/user-attachments/assets/669bdd3c-eccd-4a8f-8786-5da310b83413)

I hope that clarifies things -- please follow up with any questions :)

**Comment by mikeedjones** [comment] 2024-08-15 15:27
Thanks for the speedy response!

```
b'{"reason":"1 validation error for ObjCHInsertable\\nrefs\\n  Value error, too many values to unpack (expected 2) [type=value_error, input_value=[\'weave-trace-internal://...GEcjNbicRhmLF9o7MTvBYM\'], input_type=list]\\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error"}'
```
Is the issue we're seeing which seemed to be resolved, in some cases, by inheriting from `weave.Object` - But you're sayin that error shouldn't happen? Will look at putting out an MRE.

**Comment by gtarpenning** [comment] 2024-08-15 15:51
Hi @mikeedjones, you shouldn't be running into that pydantic validation error, which looks to be originating [here](https://github.com/wandb/weave/blob/2b686ad1a9e47f64ad19f0b53cf6510a865ea8a7/weave/trace_server/clickhouse_trace_server_batched.py#L421). Do you mind providing your installed `weave` package version? Your `wandb` username would also be helpful :) Thanks!

**Comment by mikeedjones** [comment] 2024-08-15 16:00
```
wandb==0.17.6
weave==0.50.14
```

Can we pick this up on email maybe? I can ping customer support :)

**Comment by mikeedjones** [comment] 2024-08-15 16:18
Able to reproduce with 

```
import wandb
import weave
from pydantic import AliasChoices, AliasGenerator, BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

camel_alias = AliasGenerator(
    validation_alias=lambda field_name: AliasChoices(field_name, to_camel(field_name)),
)


class Author(BaseModel):
    name: str


class Performances(BaseModel):
    genre: str
    performances: dict[str, str]


class Book(BaseModel):
    model_config = ConfigDict(alias_generator=camel_alias)
    title: str
    author: Author


@weave.op
def use_book(book: Book) -> str:
    return f"Hello, we are using {book.title} by {book.author}"


wandb.login(key="082064d4093437c04e79c11087accfdb0257a233")
weave.init(project_name="your_project")

book = Book(title="Much Ado About Nothing", author=Author(name="last: Shakespeare"))

use_book(book)

```

**Comment by mikeedjones** [comment] 2024-08-15 16:23
Able to reproduce with 

```python
import weave
from pydantic import AliasChoices, AliasGenerator, BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

camel_alias = AliasGenerator(
    validation_alias=lambda field_name: AliasChoices(field_name, to_camel(field_name)),
)


class Author(BaseModel):
    name: str


class Performances(BaseModel):
    genre: str
    performances: dict[str, str]


class Book(BaseModel):
    model_config = ConfigDict(alias_generator=camel_alias)
    title: str
    author: Author


@weave.op
def use_book(book: Book) -> str:
    return f"Hello, we are using {book.title} by {book.author}"


weave.init(project_name="your_project")

book = Book(title="Much Ado About Nothing", author=Author(name="last: Shakespeare"))

use_book(book)
```

Seems like the colon in a nested string field is the problem

**Comment by gtarpenning** [comment] 2024-08-15 17:04
@mikeedjones 

> Can we pick this up on email maybe? I can ping customer support :)

Perfect, please do. Thanks for the repro. Looking at this now.

**Comment by gtarpenning** [comment] 2024-08-15 17:16
@mikeedjones Okay, this is ticketed for internal triage (asap), but I have identified at least the surface level issue: `name` is reserved and gets used to construct that internal `weave-trace-internal://....` URI. 

Working example: 
```python
import weave
from pydantic import BaseModel


class Author(BaseModel):
    first_name: str


class Book(BaseModel):
    title: str
    author: Author


@weave.op
def use_book(book: Book) -> str:
    return f"Hello, we are using {book.title} by {book.author}"


weave.init(project_name="your_project")

book = Book(title="Much Ado About Nothing", author=Author(first_name="last: Shakespeare"))

use_book(book)
```
