### ISSUE TITLE
Weave with recursive functions

### ISSUE THREAD

**Issue by stantonius** [wandb/weave#3132] opened 2024-12-03 15:58 UTC
Hey all - loving the library.

Question about using Weave for recursive function calling. See the toy example below:

```python
@weave.op()
def recursive_function(n: int) -> int:
    if n == 0:
        return 0
    return recursive_function(n-1)

recursive_function(6)
```

The first trace sent to Weave looks to contain all the recursive function calls:

![Image](https://github.com/user-attachments/assets/ba73fe57-51ac-409e-89fc-050802fc2f58)

However it also generates 5 other traces. Is this _expected behaviour_? Or am I not thinking about this in the right way?

The use case for this recursive behaviour in the context of LLMs is multi-turn function calling (executing the function params and sending back to LLM for the next function given the last result).

Thanks

**Comment by andrewtruong** [comment] 2024-12-03 20:32
Hey @stantonius , that is expected because you're specifically filtering for the `recursive_function` op.  Here's `fib` with the same view showing all the times we called `fib` (including recursive calls):
![Image](https://github.com/user-attachments/assets/9b9489c7-1a61-4292-9cc7-7ec7e709b6a1)

If you remove the filter, you will see just the root call:
![Image](https://github.com/user-attachments/assets/b0ea38ff-b66d-4044-b0ba-5685c3e16009)
![Image](https://github.com/user-attachments/assets/506d0416-1aed-4a04-9f80-dcdd4c6a3a93)

I can see why this might be confusing though.  Did you land on this page from the 🍩 link?  Were you expecting to see just 1 call because there's just 1 🍩 link?

**Comment by stantonius** [comment] 2024-12-05 19:46
Thanks for the reply.

Yes that is exactly how I got there, by opening the 🍩 link. 

You're right - I am confused about what is being reported when I click that link vs when I view all ops, but in terms of the recursive functions tracking issue, Weave does work.

Thanks

**Comment by jamie-rasmussen** [comment] 2024-12-09 15:00
I will close this ticket since the system is behaving as designed, but we do appreciate your feedback that the call link behavior is confusing.

**Closed by jamie-rasmussen** 2024-12-09 15:00 UTC
